version: '3'
services:
    app:
        build:
            context: ./
        container_name: petshop
        volumes:
            - .:/var/www/html
            - .env:/var/www/html/.env
        ports:
            - "8082:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - petshop
        depends_on:
            - mysql


    mysql:
        image: mysql:8.0
        container_name: petshop_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: petshop
            MYSQL_ROOT_PASSWORD: 1
            MYSQL_PASSWORD: secret
            MYSQL_USER: petshop
        ports:
            - 3309:3306
        volumes:
            - 'mysql8:/var/lib/mysql'
            - './db/init.sql:/docker-entrypoint-initdb.d/01init.sql'
        networks:
            - petshop


networks:
    petshop:
        driver: bridge
volumes:
    mysql8:
        driver: local

